### ISSUE TITLE
[BUG] .ts video files give a black screen

### ISSUE THREAD

**Issue by Rejected-Peice** [ParveenBhadooOfficial/Google-Drive-Index#106]
Whenever I try to load an .ts video file, it gives a black screen instead of loading the video. I am not sure if it is the issue with plyr.io, but I dont see any issues open regarding .ts file playback. So I planned to create an issue here to check if I am the only one with this issue.

**Comment by ParveenBhadooOfficial** [comment]
> Whenever I try to load an .ts video file, it gives a black screen instead of loading the video. I am not sure if it is the issue with plyr.io, but I dont see any issues open regarding .ts file playback. So I planned to create an issue here to check if I am the only one with this issue.

@Rejected-Peice GDI uses [plyr.io](https://github.com/sampotts/plyr/issues), please make these issues on their repo.
