### ISSUE TITLE
[FEATURE REQUEST] Get file ID on the front-end

### ISSUE THREAD

**Issue by neelygenet** [ParveenBhadooOfficial/Google-Drive-Index#107]
**Is your feature request related to a problem? Please describe.**
I am trying to embed files directly from Google Drive but despite of my attempts I was not able to stringfy the current file ID to the front-end.

**Describe the solution you'd like**
Anything that would be capable to stringfy the current file ID to the front-end.

**Describe alternatives you've considered**
I am not a Workers specialist, but I've made some attempts and I'd like to request some help from anyone :-)

**Comment by ParveenBhadooOfficial** [comment]
Send a message on t.me/TheFirstSpeedster

**Comment by ParveenBhadooOfficial** [comment]
Added in Latest Release.
