### ISSUE TITLE
[FEATURE REQUEST] "Encrypt" the name of files and folders

### ISSUE THREAD

**Issue by neelygenet** [ParveenBhadooOfficial/Google-Drive-Index#112]
**Is your feature request related to a problem? Please describe.**
Yes. When a file or folder name has a special character, like `#` or `?`, the Worker returns an error (print: https://prnt.sc/123iulu). By encrypting its names with alphanumeric characters only, this should be solved.

**Describe the solution you'd like**
Instead of file path be:
`path/to/folder with # or ?/file.mp4` (Worker returns error 1101).
It can be:
`4GPY/34/GHKG3FSY6H6RKW7P6JG6/E6OWIG2R.mp4` (It would work perfectly).

**Describe alternatives you've considered**
Maybe it wouldn't be necessary to encrypt the filename literally, but simply change all possible characters by pre-chosen alphanumeric characters. Example: A could be `a`, `#` could be `6G5A`, `?` could be `8DF4`, so a file with the name `A#?.mp4` would be `a6G5A8DF4.mp4`. I think it would also solve possible problems with Asiatics alphabets.

**Additional context**
When a project has a little range of files, it is simple to solve it by simply renaming the file. But in my case, we have tons of files (about 600 thousand) so it is absolutely impossible to do this. It would simpler for us to implement a solution like this.

**Comment by ParveenBhadooOfficial** [comment]
can you confirm that # character is fixed in the latest release?

**Comment by neelygenet** [comment]
No, `#` still returning error 1101. I saw you've forked [ParveenBhadooOfficial/gd-efc-1](https://github.com/ParveenBhadooOfficial/gd-efc-1), are you trying to implement this? Do you need help? :-)

**Comment by ParveenBhadooOfficial** [comment]
Will be fixed in next update. see progress [here](https://testing-home.fetchgoogleapi.workers.dev)
