### ISSUE TITLE
[BUG] COPY button doesn't give downloadable link of the file

### ISSUE THREAD

**Issue by swapnilg4u** [ParveenBhadooOfficial/Google-Drive-Index#113]
The COPY button of the files don't give encoded links of the file.

It should give downloadable link of the file

**Comment by victorgsfigueiredo** [comment]
Probably it is a problem with an extension or your anti-virus, 'cause here it is working just fine here (both on Chromium-based browsers and Firefox).

**Comment by ParveenBhadooOfficial** [comment]
> The COPY button of the files don't give encoded links of the file.
> 
> It should give downloadable link of the file

Please Provide more information on this. Provide some links you're unable to download. This could be another problem. As we cannot encode all characters because it may not work for characters from other languages. (eg. Turkish Characters)
