### ISSUE TITLE
Stream option to Pc

### ISSUE THREAD

**Issue by telegrambotdev** [ParveenBhadooOfficial/Google-Drive-Index#122]
I saw there are some applications that are supported to open the video links on mobile. can you add that option for pc too?  Stream to vlc ,km player-like players  on pc ?

**Comment by telegrambotdev** [comment]
ps: i cant stream X265 hevc videos on browser due to limitations.if you add this streaming feature for pc , we can easily stream those videos.

**Comment by ParveenBhadooOfficial** [comment]
copy the link and stream in player stream. this doesn't needed to implement.
