### ISSUE TITLE
[FEATURE REQUEST] Reduce the gap between Navigation bar and Folder(s) stack.

### ISSUE THREAD

**Issue by wiredassistant** [ParveenBhadooOfficial/Google-Drive-Index#124]
Reduce the gap between Navigation bar and Folder(s) stack. 
![Here](https://telegra.ph/file/3e8eb1f91a99f1a73f3b2.jpg)

**Comment by ParveenBhadooOfficial** [comment]
Will be fixed in next Major Update. Bootstrap 5.

**Comment by cosmicqbit** [comment]
Sounds great, Thank you ❤️
