### ISSUE TITLE
[FEATURE REQUEST] Filter file list, sort by filename/modified time

### ISSUE THREAD

**Issue by NSKSW** [ParveenBhadooOfficial/Google-Drive-Index#125]
it will be great if these features are supported
- Filter file list
- sort by filename/modified time

**Comment by ParveenBhadooOfficial** [comment]
Fixed. [here](A comma-separated list of sort keys. Valid keys are 'createdTime', 'folder', 'modifiedByMeTime', 'modifiedTime', 'name', 'name_natural', 'quotaBytesUsed', 'recency', 'sharedWithMeTime', 'starred', and 'viewedByMeTime'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedTime desc,name. Please note that there is a current limitation for users with approximately one million files in which the requested sort order is ignored.)
