### ISSUE TITLE
How can I avoid downloading files?

### ISSUE THREAD

**Issue by mau551** [ParveenBhadooOfficial/Google-Drive-Index#126]
I want it to be only a browser, I don't want the files to be downloaded, nor displayed, I already set "disable_player": true, but still the files can be downloaded, I tried to set "protect_file_link": true, but nothing changes, how do I prevent files from being downloaded?

**Comment by ParveenBhadooOfficial** [comment]
We will add remove download button option.

**Comment by mau551** [comment]
I would appreciate if you also add an option to avoid external reproduction.

**Comment by ParveenBhadooOfficial** [comment]
> I would appreciate if you also add an option to avoid external reproduction.

explain.

**Comment by hacklido** [comment]
> We will add remove download button option.

also try to add button to stream online, like a google play button.

**Comment by ParveenBhadooOfficial** [comment]
> > We will add remove download button option.
> 
> also try to add button to stream online, like a google play button.

Explain it. Google Play Button? Streaming Player is available. Also Streaming through mobile players also available. What are you trying to say.

**Comment by wiredassistant** [comment]
> 
> 
> > We will add remove download button option.
> 
> also try to add button to stream online, like a google play button.

You mean like this?
![Preview](https://telegra.ph/file/e9ded56896f47cf4b59a9.jpg)

**Comment by hacklido** [comment]
> > > We will add remove download button option.
> > 
> > 
> > also try to add button to stream online, like a google play button.
> 
> You mean like this?
> ![Preview](https://camo.githubusercontent.com/b17b042f757bc46376fb7ca3cbc70065c28111975dfe940e484127040b6b83d1/68747470733a2f2f74656c656772612e70682f66696c652f6539646564353638393666343763663462353961392e6a7067)

exactly @ParveenBhadooOfficial i just bulled out the example for icon design. We already have a button to download videos right, adjacent to it, add this straming too... thus it will encourage streaming otherwise many don't know clicking on the title will stream the video.

**Comment by ParveenBhadooOfficial** [comment]
> > > > We will add remove download button option.
> > > 
> > > 
> > > also try to add button to stream online, like a google play button.
> > 
> > 
> > You mean like this?
> > ![Preview](https://camo.githubusercontent.com/b17b042f757bc46376fb7ca3cbc70065c28111975dfe940e484127040b6b83d1/68747470733a2f2f74656c656772612e70682f66696c652f6539646564353638393666343763663462353961392e6a7067)
> 
> exactly @ParveenBhadooOfficial i just pulled out the example for icon design. We already have a button to download videos right, adjacent to it, add this straming too... thus it will encourage streaming otherwise many don't know clicking on the title will stream the video.

this is already added beside the download button.

**Comment by ParveenBhadooOfficial** [comment]
Fixed.
