### ISSUE TITLE
[FEATURE REQUEST] Serve Google Drive direct download link instead of Cloudflare proxy on videos

### ISSUE THREAD

**Issue by neelygenet** [ParveenBhadooOfficial/Google-Drive-Index#128]
**Is your feature request related to a problem? Please describe.**
Yes. It is against Cloudflare TOS to stream videos, which includes videos using this Google Drive Index. My service was limited recently on this way.

**Describe the solution you'd like**
Instead of serving a proxied download link through Cloudflare for videos, which is against theirs TOS, serve a direct Google Drive download link.
Instead of serving `example.workers.dev/folder/file.mp4` on "Download" button, serve something like `gdriveserver.googleusercontent.com/file.mp4` (I mean the Google Drive link).

**Comment by ParveenBhadooOfficial** [comment]
`gdriveserver.googleusercontent.com/file.mp4` links are for public links or with authentication with your google account. it cannot server via API. thats why we use Cloudflare Bandwidth. You can use same account to overcome your issue. I cannot share that here.
