### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by ebubekirttr** [ParveenBhadooOfficial/Google-Drive-Index#129]
**Is your feature request related to a problem? Please describe.**
Yes, when I trying to open my videos with VLC it doesn't come up, and sometimes I can't download items with internet download manager because of the password and username.
**Describe the solution you'd like**
Links should come like https://username:password@link at the passworded accounts.

**Comment by ParveenBhadooOfficial** [comment]
Invalid.
