### ISSUE TITLE
[FEATURE REQUEST] Selecting audio in videos

### ISSUE THREAD

**Issue by cihanvol** [ParveenBhadooOfficial/Google-Drive-Index#130]
as you know some videos has dual, 3 4 audios.
if we can select audio, it'll be great.
like this in mpc-hc:

![resim](https://user-images.githubusercontent.com/63202692/117540067-097eb500-b016-11eb-85c5-4d3d5570804c.png)

**Comment by ParveenBhadooOfficial** [comment]
Cannot be done.
