### ISSUE TITLE
[FEATURE REQUEST] How to remove /:0/ Order by setting a single DriveID ??

### ISSUE THREAD

**Issue by rootxad** [ParveenBhadooOfficial/Google-Drive-Index#135]
**Is your feature request related to a problem? Please describe.**
No, i want to remove the drive order as it messes up the url. I want it clear.

**Describe the solution you'd like**
A simple Prop where users can set either multiple drive or single.

**Describe alternatives you've considered**
This one features the request i am seeking from you:
https://github.com/5MayRain/goIndex-theme-nexmoe/blob/master/GoIndex.js

**Additional context**
It would be awesome as the script itself is amazing, you have added some amazing feature, you also added a Downloaderror page which seemed encrypted by you. Hope that can be open-source one day.

**Comment by ParveenBhadooOfficial** [comment]
Requires editing of code. Won't be doing this because it isn't a real requirement.
