### ISSUE TITLE
[BUG] [Theme-level] Long file/folder names are not wrapped inside the page's table cell

### ISSUE THREAD

**Issue by rokibhasansagar** [ParveenBhadooOfficial/Google-Drive-Index#142]
**Describe the bug**
Theme Custom CSS needs to adapt somehow.
When the folder/file name has a many characters in single word, like `this-is-a-very_long_name-of-a-folder-which-overflows`, then the cell in Index page overflows.

**To Reproduce**
1. Add any really-long-named file/folder in subfolder of your index
2. View it on mobile, or open a small-width window in PC
3. See error

**Expected behavior**
The words should've split in next line, like break words then wrap. There's a CSS property about it I think 🤔

**Screenshots**
![Screenshot_20210517-100803](https://user-images.githubusercontent.com/10854164/118432261-f34db480-b6f9-11eb-8540-41de2eeb58d6.png)

**Version (please complete the following information):**
 - Latest, the "alpha-17" version. I updated Index yesterday from your generator.

**Additional context**
This bug might not be Internal but only theme-related 🤔

**Comment by ParveenBhadooOfficial** [comment]
telegram @TheFirstSpeedster, send message here with your Index Link to test this.

**Comment by ParveenBhadooOfficial** [comment]
@mayank629 give me a link to check

**Comment by ParveenBhadooOfficial** [comment]
Fixed in Next Release

**Comment by ParveenBhadooOfficial** [comment]
Check Here https://testing.fetchgoogleapi.workers.dev/0:/
