### ISSUE TITLE
Search Bar Is Not Showing

### ISSUE THREAD

**Issue by risfat** [ParveenBhadooOfficial/Google-Drive-Index#143]
Google-Drive-Index's search bar is showing for " root " but when I put an id of a specific folder it doesn't show the search bar! So Any Fix For that?

![image](https://user-images.githubusercontent.com/47077958/118433609-2f364900-b6fd-11eb-94f3-523e7435fab9.png)

**Comment by ParveenBhadooOfficial** [comment]
Invalid. Read the Guide.
