### ISSUE TITLE
[BUG] Video format MKV doesn't have audio

### ISSUE THREAD

**Issue by muazsyahrul** [ParveenBhadooOfficial/Google-Drive-Index#144]
**Describe the bug**
Video that file format .mkv doesn't have sound but the video was good. Video format .mp4 have audio and video. It seem like player that built in website have a problem.

**Version :**
 - 2.0.18
 - alpha-17

**Additional context**
I try to use external player such as VLC player but it doesn't want to play it at all.

**Comment by ParveenBhadooOfficial** [comment]
https://stackoverflow.com/questions/14988638/no-sound-while-playing-mkv-with-html5
