### ISSUE TITLE
[FEATURE REQUEST] Have media packaged & served like a Media Centre (Jellyfin/Plex etc.)

### ISSUE THREAD

**Issue by atmos-o** [ParveenBhadooOfficial/Google-Drive-Index#145]
A lot of us likely have media sorted into folders for Movies & TV Shows in separate locations, following a specific naming & sorting format. So different apps know where to look for what. 
It would usually look something like this for a movie in the folder `/movies/A Scanner Darkly (2006)/`
\- additional subtitles files & poster images in the same folder location for the media. 

![image](https://user-images.githubusercontent.com/44858581/118653562-94626b00-b7df-11eb-9f88-a142e23b8d59.png)

What if instead of being given a simple view of folder locations it was presented & packaged nicely. Looking something like this: 
![image](https://user-images.githubusercontent.com/44858581/118648003-ddafbc00-b7d9-11eb-8de6-3ba75bb17b33.png)
Clicking on the poster image would load to the video viewing page, & maybe clicking the name/title of the movie below the folder takes you to the default view page we currently have. 

GDindex can look for images in the same folder labelled "poster" and set that as thumbnail. Use the folder name to name the movies (can get fancy by looking for the first 4 digit number to set date separately :D)
Maybe even read the .nfo file if you can, to extract information. Information like this is stored inside:
```
<movie>
  <title>10 Cloverfield Lane</title>
  <originaltitle>10 Cloverfield Lane</originaltitle>
  <sorttitle>10 cloverfield lane</sorttitle>
  <plot>After getting in a car accident, a woman is held in a shelter with two men, who claim the outside world is affected by a widespread chemical attack.</plot>
  <tagline />
  <runtime>104</runtime>
  <thumb aspect="poster" preview="https://image.tmdb.org/t/p/original/84Dhwz93vCin6T1PX6ctSvWEuNE.jpg">https://image.tmdb.org/t/p/original/84Dhwz93vCin6T1PX6ctSvWEuNE.jpg</thumb>
  <fanart>
    <thumb preview="https://image.tmdb.org/t/p/original/cRuf19zh0OHFGWVA9Q8Bipgavv2.jpg">https://image.tmdb.org/t/p/original/cRuf19zh0OHFGWVA9Q8Bipgavv2.jpg</thumb>
  </fanart>
```
Won't even need to implement a MovieDB API integration with just this one file.

There's a lot of ideas I'd like to throw out but might be a bit too much 😄 stuff like having video view page filled with synopsis it grabs from .nfo file etc.
Some ideas I have that I understand will require a backend, and for someone like me who has a place to set it up I would love to have those possibilities.

**Comment by ParveenBhadooOfficial** [comment]
Requires too much work from user side, they'll need to organize data and posters as per this structure which is not possible for everyone. Even i cannot organize my drives this way due to lack of time.

**Comment by atmos-o** [comment]
Here's the thing, I did not do this manually. I use Sonarr & Radarr. I just add which media I want downloaded & it does everything automatically. 
Downloads into `/movies` or `/shows` folder, puts in "Season" folder if I select that option, downloads image files too. It has active dev teams, has API & modular parts to it so you can directly query the app for details. There's even a app to grab subtitles. There are thousands of us who use these - check out the community for those apps if you can spare the time. 

A lot more people have their media like this then you may know. What about Plex/Emby/Jellyfin users? They have to have their media like that for those apps to be able to work. That's thousands of people who do have media arranged like this. It could be a big thing in my opinion if more of these options were given.

**Comment by NSKSW** [comment]
You can have a look at this index
https://github.com/tks18/gindex-v4

**Comment by xd003** [comment]
> Here's the thing, I did not do this manually. I use [Sonarr](https://github.com/Sonarr/Sonarr) & [Radarr](https://github.com/Radarr/Radarr). I just add which media I want downloaded & it does everything automatically. Downloads into `/movies` or `/shows` folder, puts in "Season" folder if I select that option, downloads image files too.
> It has active dev teams, has API & modular parts to it so you can directly query the app for details. There's even a app to grab subtitles (https://wiki.servarr.com more here) There are thousands of us who use these.
> 
> A lot more people have their media like this then you may know. Think about Plex/Emby/Jellyfin users. They have to have their media like that for those apps to be able to work. That's thousands of people who do have media arranged like this. It could be a big thing in my opinion if more of these options were given.
> 
> edit: I can show you my setup of this in action if you're not understanding it fully.

All of this is still way is way too much for like average 95% of index users. If someone is having a vps with sonarr and radarr automation , then why won't they simply use the Mediaserver itself . It makes literally zero sense for someone with sonarr , radarr and wanting to use this index . No matter how much work goes into index , you can never expect it to be as good as plex/emby .. Its not really worth at all

**Comment by atmos-o** [comment]
> All of this is still way too much for like average 95% of index users. 

It really is not too much. All the *Arr services are on the same difficulty level as setting an Index up (*Arr being Sonarr & Radarr). And even then thats not needed, a person could manually have arranged media like this - which I did before when downloading media manually. Poster's come with a lot of releases these days too. There are also basic programs that organise like this. There is a far greater number of *Arr service  users than there are G-Index ones. 

> If someone is having a vps with sonarr and radarr automation , then why won't they simply host the Mediaserver as well. It makes literally zero sense for someone with sonarr , radarr and wanting to use this index. 

Try hosting your own media on your System - No guaranteed 100% uptime & you can't match the CDN of CF & Google combined.
I have my server at home. If I have Plex on my home system I would run into issues if I have a few people using it at same time. Serving the media would put a strain on my bandwidth & resources. *Arr services can run on small systems without affecting performance so it doesn't take a big machine to do it. 
I can have my setup turn on once a day for a few hours to grab media if there is any & sleep, saving me money. If I set up Plex with it I would need to always have it on. 

> It defeats the very purpose of your collection and content automation setup.

No it does not? All this grabs & sorts your media & then it gets move to GDrive. Plex is separate from this process completely.

> No matter how much work goes into index , you can never expect it to be as even remotely as good as plex/emby .. Its not really worth at all

This feature request was to get it as close to it as can be. We already have another Index that can use thumbnail view, this Index finds subtitle files and loads it in plyr script, logically it could set a thumbnail of a poster.jpg found in same location or of same name. It can get pretty close to 'as good as Plex'.

**Comment by xd003** [comment]
> Try hosting your own media on your System - No guaranteed 100% uptime & you can't match the CDN of CF & Google combined.
> I have my server at home. If I have Plex on my home system I would run into issues if I have a few people using it at same time. Serving the media would put a strain on my bandwidth & resources. *Arr services can run on small systems without affecting performance so it doesn't take a big machine to do it.
> I can have my setup turn on once a day for a few hours to grab media if there is any & sleep, saving me money. If I set up Plex with it I would need to always have it on.

Well obviously if someone would host plex/emby on their primary home machine it would hog quite a lot of resources . Hence i said ```If someone have hosted sonarr/radarr on a vps , its way better to host plex as well``` . Mediaservers in general are meant to be hosted remotely on a vps or a dedicated machine that's On 24*7 and reserved specially for mediaserver. 

Why i said particularly that's its not worth doing it in this index is because it was never really made for something like in first place .it would be way too much of a change, stuff will break a lot and its really out of scope.  I bet making a index designed for such purpose from scratch would be much better than turning a normal one into it ( see libdrive linked below for instance ) . I myself have both plex and emby running on my vps with sonarr , radarr and everything so can very well judge the differences

 if you don't have a vps and want a somewhat mediaserver like feel , you can use this - https://github.com/libDrive/libDrive . It can be hosted on heroku so you don't need to pay . Although keep your expectations limited . An index like this or python project like libdrive by no means can be compared to plex/emby , although currently libdrive is somewhat closest you can get . Mediaservers are commerical projects with developers working on it full time , i do respect each project but just saying realistically

**Comment by atmos-o** [comment]
LibDrive is basically it. Thanks for linking us this.
