### ISSUE TITLE
How To Fix Loading Issue

### ISSUE THREAD

**Issue by gigi147** [ParveenBhadooOfficial/Google-Drive-Index#154]
It was working fine, but now it keeps loading & the files are not shown. Any Solution?

![Screenshot 2021-05-23 003731](https://user-images.githubusercontent.com/83132257/119238262-1eebf700-bb5f-11eb-9844-7631c27b4f81.png)

**Comment by 4zjata** [comment]
Also happend to me, after going to worker i find this 

> Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at googleDrive._findDirId (worker.js:743)
    at async googleDrive.findPathId (worker.js:714)
    at async googleDrive.list (worker.js:502)
    at async apiRequest (worker.js:341)
_findDirId @ worker.js:743
Promise.then (async)
(anonymous) @ worker.js:191


I'm not sure what it means but maybe it will help

**Comment by ParveenBhadooOfficial** [comment]
Generate Code.
