### ISSUE TITLE
[FEATURE REQUEST]  .Password file

### ISSUE THREAD

**Issue by RAJESHWARPRASAD1** [ParveenBhadooOfficial/Google-Drive-Index#160]
How to create I mean what is this .Paasword file how to make and what's format

**Comment by ParveenBhadooOfficial** [comment]
https://github.com/ParveenBhadooOfficial/Google-Drive-Index#use-of-password-file

https://github.com/ParveenBhadooOfficial/Google-Drive-Index/wiki/Getting-Started-with-gdi.js.org

Always Read Before asking...
