### ISSUE TITLE
[BUG] Return to drive 0: after clicking breadcrumb

### ISSUE THREAD

**Issue by devsdocs** [ParveenBhadooOfficial/Google-Drive-Index#161]
**Describe the bug**
Everywhere when breadcrumb clicked, the page always return to base folder of drive 0:

**To Reproduce**
1. Go to 'any subfolder'
2. Click on 'breadcrumb'
3. See error

**Expected behavior**
When breadcrumb is clicked, we want to navigate to that folder, not to drive 0:

**Screenshots**
None

**Version (please complete the following information):**
2.0.18

**Additional context**
None

**Comment by ParveenBhadooOfficial** [comment]
Eg. https://testing.fetchgoogleapi.workers.dev/0:/FolderWith[brackets]/

works fine for me.

**Comment by devsdocs** [comment]
Can you try multiple drive? Navigate (via breadcrumb) to folder/subfolder in drive id other than 0:

**Comment by ParveenBhadooOfficial** [comment]
> Can you try multiple drive? Navigate (via breadcrumb) to folder/subfolder in drive id other than 0:

https://testing.fetchgoogleapi.workers.dev/1:/Folder/

i recommend generating code and trying without changing anything in code except required data.
