### ISSUE TITLE
search url problem.

### ISSUE THREAD

**Issue by magneto261290** [ParveenBhadooOfficial/Google-Drive-Index#17]
![Capture](https://user-images.githubusercontent.com/54003800/93068024-92b53600-f699-11ea-94c5-75b554611f91.PNG)

after searching it gives a preview url (?a=view) for non preview able files also (like zip files).

**Comment by ParveenBhadooOfficial** [comment]
Thanks, will fix that.

**Comment by ParveenBhadooOfficial** [comment]
Fixed.
