### ISSUE TITLE
Arc.io says incomplete installation .

### ISSUE THREAD

**Issue by Hey767** [ParveenBhadooOfficial/Google-Drive-Index#184]
Custom domain is registered plus arc.io code has also beem added in cloudfare please resolve

**Comment by ParveenBhadooOfficial** [comment]
This is not arc.io support or Cloudflare support.

PS: Try Setting SSL to Full (Strict) in Cloudflare SSL Settings

**Comment by Hey767** [comment]
> This is not arc.io support or Cloudflare support.
> 
> PS: Try Setting SSL to Full (Strict) in Cloudflare SSL Settings

Thanks 😊 it worked for me!!
