### ISSUE TITLE
PDF Viewer Doesn't Wrok...

### ISSUE THREAD

**Issue by VarnaX** [ParveenBhadooOfficial/Google-Drive-Index#199]
![Screenshot 2021-06-18 121306](https://user-images.githubusercontent.com/56477171/122518297-a463a980-d02e-11eb-9d29-58b93e014819.png)

**Comment by ParveenBhadooOfficial** [comment]
Depends on this for now.
https://cdn.jsdelivr.net/gh/mozilla/pdf.js@gh-pages/build/pdf.js


will update with new version soon.
