### ISSUE TITLE
Markdown not rendering?

### ISSUE THREAD

**Issue by Darthagnon** [ParveenBhadooOfficial/Google-Drive-Index#21]
Is there some code I need to edit for markdown to render? It doesn't seem to, though I saw some commits related to markdown rendering. Currently, presence of a ```.md``` file causes the worker to go into an infinite loading loop (the worker will load a folder with a ```.md``` once, then infinite load if you try again).

**Comment by ParveenBhadooOfficial** [comment]
Fixed.

Preview at https://light-demo.ve.workers.dev/0:/

Incase you're still having problems please comment your Demo Worker Link.

**Comment by Darthagnon** [comment]
Here's my test:
https://download.remirror.workers.dev/0:/test/
u: jacksparrow, p: cs.rin.ru

Testing the update.

**Comment by ParveenBhadooOfficial** [comment]
Cdn links for master doesn't get updated even if i change here. That's why it's happening. Use version 2.0.1 for now.

**Comment by AbirHasan2005** [comment]
> Fixed.
> 
> Preview at https://light-demo.ve.workers.dev/0:/
> 
> Incase you're still having problems please comment your Demo Worker Link.

Sir, please fix that README.md file not Rendering problem 😭😭😭

If you could fix that this index maker will be very good looking.

Example Website:
https://tgindex.hackitabirhasan.workers.dev/0:/

**Comment by ParveenBhadooOfficial** [comment]
Fixed.
