### ISSUE TITLE
How to Deploy on Local With Node JS

### ISSUE THREAD

**Issue by NEOIR** [ParveenBhadooOfficial/Google-Drive-Index#22]
Hi, Can i Deploy this Repo With NodeJS on my Coputer

Like That npm install and Then npm start Command ?

Thanks.

**Comment by ParveenBhadooOfficial** [comment]
I'm only UI Designer for this project. So Don't know about that one.

**Comment by Rejected-Peice** [comment]
I recommend you to take a look at this
You can store the repo files and redirect the links in the code to the local paths

**Comment by neelygenet** [comment]
Take a look on https://github.com/gja/cloudflare-worker-local
