### ISSUE TITLE
Combined search across all root IDs

### ISSUE THREAD

**Issue by viper-adnan** [ParveenBhadooOfficial/Google-Drive-Index#24]
Add a option to enable combined search so the search shows results from all root ids.

**Comment by ParveenBhadooOfficial** [comment]
@viper-adnan Will try this, incase you know please make a pull request.

**Comment by ParveenBhadooOfficial** [comment]
Requires rewriting of code by some JS expert. Maybe I'll do this in future if i learned JS.
