### ISSUE TITLE
How disable the download button?

### ISSUE THREAD

**Issue by ZeroCool22** [ParveenBhadooOfficial/Google-Drive-Index#25]
Hi, can you tell me please how i can deactivate the **Download button**?

![Screenshot_1](https://user-images.githubusercontent.com/13344308/94476139-712e7100-01a6-11eb-852a-6a610799046f.png)

Thx.

**Comment by ParveenBhadooOfficial** [comment]
will bring that feature.

**Comment by ZeroCool22** [comment]
Nothing yet?

**Comment by ParveenBhadooOfficial** [comment]
> Nothing yet?

coming in next few days.

**Comment by ZeroCool22** [comment]
> 
> 
> > Nothing yet?
> 
> coming in next few days.

Thx!
