### ISSUE TITLE
Feature Request: Multipule users

### ISSUE THREAD

**Issue by Crenshaw1312** [ParveenBhadooOfficial/Google-Drive-Index#29]
is it possible to have multipule usernames, and corresponding passwords for one drive? if so how?

**Comment by ParveenBhadooOfficial** [comment]
Please explain further.

**Comment by Crenshaw7860** [comment]
So it's possible to have a needed username and password to access the index, but what if I want multiple usernames with their own password
So,
Username: Doggo
Password: DogsRBest

Username: Cat
Password: CatsRBest

But I would like it so the combination CANT be
Username: Doggo
Password: CatsRBest

**Comment by ParveenBhadooOfficial** [comment]
Will test this using array. Won't add in Code but will provide a solution in readme.

**Comment by ParveenBhadooOfficial** [comment]
Added.
