### ISSUE TITLE
Feature Requests, Json, Bookmarking, Theming, Home Improvement, Making Shortcuts Work, GDrive Linking

### ISSUE THREAD

**Issue by Crenshaw1312** [ParveenBhadooOfficial/Google-Drive-Index#31]
# .JSON format
On imgur, you can apply `.json`  ot the end of the url to get a feed, take for example [r/dankmemes on imgur](https://imgur.com/r/dankmemes/hot.json).
> Search Query results

Date created, Size, Content, Path string, Path URL, Used/Play Count, Name, File type
> Folder view

for a folder it should just be the Name, Path string, Path URL, Date created

# Bookmark
Sure you can do this via bookmarking it on your browser
but having another dropdown that can take you to you bookmarks for that drive is much more convenient. The bookmark button could appear when you hover of a file or folder to the right as a glph maybe?

# Theming
Right now there is only light mode and dark mode, condider adding more if it's possible, like if the color is naturally darker use white text, if it's lighter use black text

# Home Improvement
when you click on home, it takes you to the home of the Drive, I think it would make more sense if home would take you to a "gallery" of all of the drives on the index instead. ONLY if the index has more than one drive though.

# Shortcuts
Google has shortcuts that you can have to get from place to place quicker, although when using it through the index it doesn't work! Have it work so it'd put you where ever the short cut would go.

# Link to actual GDrive
In the footer section add a link that connects it to the location you're currently in the actual Google Drive.
so it'd be something like `https://drive.google.com/path/thing...`

**Comment by ParveenBhadooOfficial** [comment]
Some are Done, Some are work in progress, Some are dropped. 🖌️
