### ISSUE TITLE
can i host this?

### ISSUE THREAD

**Issue by Dhanamerdeka** [ParveenBhadooOfficial/Google-Drive-Index#36]
Hello anyone...
umm can i host this script on my server?
i dont know how to implement this... anyone can help me?
of course i will give you something for this...

**Comment by ParveenBhadooOfficial** [comment]
use https://generator.driveindex.ga

**Comment by Dhanamerdeka** [comment]
@ParveenBhadooOfficial ummm i mean for hosting
not cloudflare worker...
can i do that?
