### ISSUE TITLE
Wrong File Size

### ISSUE THREAD

**Issue by Miteshmnu** [ParveenBhadooOfficial/Google-Drive-Index#38]
It shows wrong file size.

Ex.
  File Size in bytes  :  4,465,782,334 bytes
              size in GB  :  4.159 GB
 IN Index it shows  :  4.47GB

So, Please fix this problem.

**Comment by Rejected-Peice** [comment]
Yes, this issue is there
I just noticed it :P

**Comment by ParveenBhadooOfficial** [comment]
@Miteshmnu In size is in GiB not GB. It's correct.
