### ISSUE TITLE
Feature Request: Ability to download an entire folder and display folder sizes

### ISSUE THREAD

**Issue by Rejected-Peice** [ParveenBhadooOfficial/Google-Drive-Index#42]
I would like to see an option to download an entire folder at once.
Example like this (https://www.directorylister.com/)

Also, if that feature gets added, then the ability to check folder sizes will be good.

**Comment by ParveenBhadooOfficial** [comment]
I'm only UI Designer for this project. Also Cloudflare workers doesn't provide server side space to zip these files and download. But I'll look into directorylister for this.

**Comment by ParveenBhadooOfficial** [comment]
Bot possible with this, as file are directly downloaded and not stored in Cloudflare backend to process this. Use Telegram Bots to do these things.
