### ISSUE TITLE
PDF reader is not rendering in the latest release (2.0.7)

### ISSUE THREAD

**Issue by Rejected-Peice** [ParveenBhadooOfficial/Google-Drive-Index#43]
![image](https://user-images.githubusercontent.com/62835853/105655446-0f78dc00-5ee6-11eb-9351-ee302bf168a5.png)

PDF reader that used to be there in the older versions are not being rendered now.
Tried in chrome and firefox, still there is issue

**Comment by ParveenBhadooOfficial** [comment]
Fixed.
