### ISSUE TITLE
Error 1101

### ISSUE THREAD

**Issue by BlackBox-cmd** [ParveenBhadooOfficial/Google-Drive-Index#48]
![Screenshot_2021-02-23 Worker threw exception ns3.moviefreak3.workers.dev Cloudflare](https://user-images.githubusercontent.com/64696205/108761248-cfeeef80-7578-11eb-9c17-03407ad160a4.png)

**Comment by bbenance** [comment]
i had the same issue when trying to download a file that had a problematic character in it (in my case it was #) 
try removing special formatting and similar characters and see if the error disappears

**Comment by ParveenBhadooOfficial** [comment]
what @bbenance said and sometimes cloudflare bans workers acc. change acc if not solved.
