### ISSUE TITLE
Allow file embed from certain url

### ISSUE THREAD

**Issue by devsdocs** [ParveenBhadooOfficial/Google-Drive-Index#49]
Can this method applied to drive index? In context that some will easily hotlinking files from index, which mean increasing in file usage.

**Comment by victorgsfigueiredo** [comment]
Could you explain better what are you trying to do?
If you are trying to embed a file from your index on another site, you can simply use the download link to make a `video` tag.

Example:

```html
<head>
  <link rel="stylesheet" href="https://cdn.plyr.io/3.6.7/plyr.css" />
</head>

<video id="player" width="100%" height="100%">
  <source src="https://downloadurl.workers.dev/file.mp4" type="video/mp4" />
</video>

<script src="https://cdn.plyr.io/3.6.7/plyr.polyfilled.js"></script>
<script>
  const player = new Plyr('#player');
</script>
```

This would embed a file from your Worker with Plyr at any other website.

**Comment by devsdocs** [comment]
Only allow abc.com to embed  file (like videos).
Does not allow xyz.com or any other domain to embed files. If any other domain trying ro embed. This will return error.
