### ISSUE TITLE
Pdf And Pptx İnternal Playback

### ISSUE THREAD

**Issue by kamileecher** [ParveenBhadooOfficial/Google-Drive-Index#54]
Can you add internal pdf, doc, pptx playback and display?

**Comment by ParveenBhadooOfficial** [comment]
PDF already disaplay in latest release.

**Comment by kamileecher** [comment]
No bro, it doesn't work properly. You can check it.

15 Mar 2021 Pzt 13:12 tarihinde Parveen Bhadoo ***@***.***>
şunu yazdı:

**Comment by ParveenBhadooOfficial** [comment]
works fine for me. Present some screenshots.
