### ISSUE TITLE
Add to subtitles cc options and player options

### ISSUE THREAD

**Issue by kamileecher** [ParveenBhadooOfficial/Google-Drive-Index#57]
![Screenshot_2](https://user-images.githubusercontent.com/58888200/111107387-ce0cc080-8567-11eb-8817-611b64604106.png)
![Screenshot_3](https://user-images.githubusercontent.com/58888200/111107560-1af09700-8568-11eb-9760-821dc842e6c4.png)

LINK

https://github.com/sampotts/plyr#options
https://aplayer.js.org/#/home?id=options

**Comment by hsj51** [comment]
In the 2nd screenshot, which index is it?

**Comment by mau551** [comment]
> En la segunda captura de pantalla, ¿qué índice es?

I think this is it: https://github.com/alx-xlx/goindex It seems to me that this topic is the first, the one that says "Aicirou / goindex-theme-acrou"

**Comment by kamileecher** [comment]
Yes bro

17 Mar 2021 Çar 00:43 tarihinde mau551 ***@***.***> şunu
yazdı:
