### ISSUE TITLE
Feature Request: To add external player support for windows and andriod 

### ISSUE THREAD

**Issue by eldronnunes** [ParveenBhadooOfficial/Google-Drive-Index#59]
I would like to see an option to stream audio and video files with external player (i.e. mx player and vlc  player )
For Example (https://ossdev.node6.workers.dev/0:video/LzA6L1ZpZGVvcy9EZW1vbiBMb3JkLm00dg)

**Comment by ParveenBhadooOfficial** [comment]
Will add in next update sir. work in progress.
