### ISSUE TITLE
It shows wrong file size.

### ISSUE THREAD

**Issue by BlackBox-cmd** [ParveenBhadooOfficial/Google-Drive-Index#63]
Ex.......
File Size in bytes : 4,465,782,334 bytes
size in GB : 4.159 GB
IN Index it shows : 4.47GB

So, Please fix this problem.

**Comment by mbassiouny33** [comment]
Dude... the apps shows things correctly, 

4,465,782,334 bytes is 4.465782334 therefore ~4.47
(see [google](https://www.google.com/search?q=4%2C465%2C782%2C334+bytes+in+GiB&sxsrf=ALeKk03M2l-Tr5bCJPcv1BAzdOmbWbbuhg%3A1616872516770&ei=RIRfYKPXLuOr1fAPrLWAOA&oq=4%2C465%2C782%2C334+bytes+in+GiB&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANQq_wBWKv8AWDA_gFoAXACeACAAa4BiAG5ApIBAzAuMpgBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=gws-wiz&ved=0ahUKEwijiYnAl9HvAhXjVRUIHawaAAcQ4dUDCA4&uact=5)

What you mean is 
 4,465,782,334 bytes = 4.159. GiB (not GB)

**Comment by ParveenBhadooOfficial** [comment]
Thanks @mbassiouny33
