### ISSUE TITLE
[Doubt] About requests...

### ISSUE THREAD

**Issue by ZeroCool22** [ParveenBhadooOfficial/Google-Drive-Index#64]
When we download a file trough the Worker, in google drive this download don't count right or it counts?

Because the other day 1 files was downloaded too much time in Google Drive but then i tried to download it from the worker, and it downloaded without problems.

This mean, the download counts are counted **separately** from Worker and Google Drive?

Thx in advance!

**Comment by ParveenBhadooOfficial** [comment]
Google Quotas are not fixed and fluctuates all the time. This is possible that when you downloaded from Index the limit was already resettled. But I'm not sure as their is no fixed documentation on Limits.
