### ISSUE TITLE
Feature Request: Add support for User-provided clientId and clientSecret in Generator

### ISSUE THREAD

**Issue by rokibhasansagar** [ParveenBhadooOfficial/Google-Drive-Index#65]
#### Using your app's `clientId` and `clientSecret` is not good for all security-concerned users.

A user should use his own app to connect to his GDrive. Therefore, he needs to use his own `clientId` and `clientSecret`.

So, you can add custom input field in the Index Generator Page where we can input those values before generating our final index script.

> You can add more custom input fields such as `contact_link`, `company_name`, etc. for user's ease.

**Comment by ParveenBhadooOfficial** [comment]
use this at cloudflare.
make it using your own client details.

https://github.com/ParveenBhadooOfficial/Google-Drive-Index/blob/master/worker/worker-generator.js

While i'll add this in one generator for direct access.
