### ISSUE TITLE
[Feature Request] Subtitle Options

### ISSUE THREAD

**Issue by vomeraine** [ParveenBhadooOfficial/Google-Drive-Index#68]
Hello,
Can I want 2 more thing about subtitle option?
First of all could you make auto external subtitle adding request as VLC or PLEX doing. To make it clear, they are recognizing the caption like this: [Video_Name].[Language_Code].[File Extention]
AFAIK other video players (nplayer, mpc-hc) are using external subs this way too,
This country code pages could be useful: [Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
ISO-639-1 codes for 2-letter
ISO-639-2/B codes for 3-letter.

Second one is can you add a load custom subtitle section. It would be better to add subtitle from pc, Thank you ^_^!!!!

**Comment by ParveenBhadooOfficial** [comment]
Added in latest release.

**Comment by vomeraine** [comment]
Could you add the Turkish option? it has tur - TR in iso code
Thanks!
