### ISSUE TITLE
Different Password for different username else only password option

### ISSUE THREAD

**Issue by viper-adnan** [ParveenBhadooOfficial/Google-Drive-Index#69]
What the need of username ? If you can't set different password for different username. 
Either add option to set different password for different username or only password option.

**Comment by ParveenBhadooOfficial** [comment]
empty username doesn't works for some browsers.

**Comment by ParveenBhadooOfficial** [comment]
Added Support for Multiple Users and Empty Auth (page asks for auth but no id pass required)

**Comment by viper-adnan** [comment]
Cool 👌🏻

**Comment by viper-adnan** [comment]
Where is the commit btw ?
