### ISSUE TITLE
No sound on MKV files

### ISSUE THREAD

**Issue by vomeraine** [ParveenBhadooOfficial/Google-Drive-Index#71]
Is it just for my files or do you have this problem too? I can play just mp4 files. mkv videos are playing but no audio with them.

**Comment by mbassiouny33** [comment]
- did you try downloading the file locally and check it actually have working audio?
- does the video have ac3 audio? ac3 may not work in a lot of browsers because of issues with licensing to Dolby

**Comment by ParveenBhadooOfficial** [comment]
@vomeraine GDI uses [plyr.io](https://github.com/sampotts/plyr/issues), please make these issues on their repo.
