### ISSUE TITLE
Can you pls solve this cannotDownloadAbusiveFile issue

### ISSUE THREAD

**Issue by Naim120** [ParveenBhadooOfficial/Google-Drive-Index#75]
![Screenshot_20210419-164839_Chrome](https://user-images.githubusercontent.com/47737443/115228371-4cdcb680-a12f-11eb-987c-64c2132fbe2f.jpg)
Showing that, this file contains malware, even it's not. It's just a video file (A GOT episode). Can you pls solve this? Thank you.

**Comment by ParveenBhadooOfficial** [comment]
Copy this file using create a shortcut and then download. It'll work.
