### ISSUE TITLE
#bug Pdf files are not readable in mobile browsers

### ISSUE THREAD

**Issue by elegantsunny10** [ParveenBhadooOfficial/Google-Drive-Index#78]
Sir, 
PDFs are not supporting in mobile browsers in latest 2.0.15 build. I have checked another builds too none of them are supporting. Please fix this.

**Comment by elegantsunny10** [comment]
![Uploading Screenshot_20210420-104631.jpg…]()

**Comment by elegantsunny10** [comment]
![Screenshot_20210420-104631](https://user-images.githubusercontent.com/75873801/115385671-04d49700-a1f6-11eb-9223-970ebf25eb64.jpg)

**Comment by ParveenBhadooOfficial** [comment]
fixed in #102
