### ISSUE TITLE
#bug videos cant be played or downloaded whose names are having big bracket []

### ISSUE THREAD

**Issue by elegantsunny10** [ParveenBhadooOfficial/Google-Drive-Index#80]
Sir,
Videos who have big brackets [ ] in the their title or in the folder name can't be played or downloaded....this id happening with only this special character...else all the characters are working fine...also this was not the issue in earlier releases.
Pls check and solve.

**Comment by ParveenBhadooOfficial** [comment]
working fine. provide some links to investigate.

**Comment by elegantsunny10** [comment]
Cant share my workers link publically.... share your personal contact aur mail so that can share the bug with you.

**Comment by ParveenBhadooOfficial** [comment]
Send Message on [Telegram](https://g.telegram.ind.in/TheFirstSpeedster)

**Comment by ParveenBhadooOfficial** [comment]
> Sir,
> Videos who have big brackets [ ] in the their title or in the folder name can't be played or downloaded....this id happening with only this special character...else all the characters are working fine...also this was not the issue in earlier releases.
> Pls check and solve.

Wrong Info Provided. Problem was with VLC which isn't mentioned here. File is being downloaded with no problem.
