### ISSUE TITLE
add Index statistic

### ISSUE THREAD

**Issue by kamileecher** [ParveenBhadooOfficial/Google-Drive-Index#92]
Example
Total File: 5000
 Total Folders: 100
 Total Size: 100GB
 Index Size: 5TB

**Comment by ParveenBhadooOfficial** [comment]
provide some Google APIS links to work with this, if possible.

**Comment by devsdocs** [comment]
Some reference https://stackoverflow.com/a/36002384

**Comment by ParveenBhadooOfficial** [comment]
> Some reference https://stackoverflow.com/a/36002384

Too old. Drive API is updated a lot after this.

**Comment by ParveenBhadooOfficial** [comment]
Invalid.
